const express = require("express");
const system = require("../controllers/systemController");
const { asyncHandler } = require("../utils/asyncHandler");
const { requireAuth } = require("../middleware/auth");
const router = express.Router();
router.get("/health", asyncHandler(system.health));
router.get("/health/extended", asyncHandler(system.extended));
router.get("/system/db-info", asyncHandler(system.dbInfo));
router.get("/system/smtp-info", asyncHandler(system.smtpInfo));
router.get("/system/email-diagnostics", asyncHandler(system.emailDiagnostics));
router.get("/system/whatsapp-diagnostics", asyncHandler(system.whatsappDiagnostics));
router.get("/system/chat-diagnostics", requireAuth, asyncHandler(system.chatDiagnostics));
router.get("/system/ai-cost-diagnostics", requireAuth, asyncHandler(system.aiCostDiagnostics));
router.get("/system/client-context", asyncHandler(system.clientContext));
router.post("/system/client-error", asyncHandler(system.clientError));
router.post("/system/chat-cache/purge-expired", requireAuth, asyncHandler(system.purgeExpiredChatMessages));
router.get("/system/status", asyncHandler(system.status));
router.get("/system/flags", asyncHandler(system.flags));
module.exports = router;
